### ISSUE TITLE
Major updates needed for lab 6

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#10]
Lab 6 is a copy of content from a previous HOL guide. This needs to be redone entirely using components of the planespotter application to illustrate essentially the same concepts that were covered in the PKS HOL guide

**Comment by natereid72** [comment]
This is resolved, per https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/BonusLabs/Deploy%20Planespotter%20Lab
