### ISSUE TITLE
Lab 7 major updates

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#11]
Lab 7 has only general basic setup guidance, this needs to be redone in the lab guide format with appropriate level of detail providing exact steps and screenshots for successful deployment in pks-ninja lab environment. Also additional steps are needed for how to setup basic initial dashboard/overview in wavefront once connected.

**Comment by natereid72** [comment]
I just opened another issue regarding subscription access. I'd be happy to go through a write-up for this lab. Is https://confluence.eng.vmware.com/display/PS/Wavefront+Quickstart the correct place for me to request access?
