### ISSUE TITLE
.corp.local DNS resolution from cli-vm 

### ISSUE THREAD

**Issue by natereid72** [CNA-Tech/PKS-Ninja#20]
Need to modify file in cli-vm template:

Edit /etc/nsswitch.conf
Change: "hosts: files mdns4_minimal [NOTFOUND=return] dns"
To: "hosts: files dns"

**Comment by natereid72** [comment]
Same DNS client config exists in v10 template. Same resolution above corrects it.

**Comment by afewellvmware** [comment]
Fixed with Nate's Patch, closing
