### ISSUE TITLE
OneCloud Sandbox Breach

### ISSUE THREAD

**Issue by humboldthacker** [CNA-Tech/PKS-Ninja#200]
The following vApps have resource allocations in excess of the thresholds configured by your OneCloud tenant administrator: PKSNinjaEnvironments

Please reduce the resource allocations for your vApp(s) below the following threshold:
CPU#=90, Memory(GB)=180, Storage(GB)=1000

**Comment by afewellvmware** [comment]
This is a known issue but should be benign, my understanding with these is that warnings for storage violations are only warnings and should not cause any problems. 

You cant even load up the hol for vsphere 6.7 whats new without violating these limits, but the team doesnt seem to want to change the warning, even though they know and even help promote the pks template. 

So you should be able to just ignore this fine. There are some onecloud orgs that people have reported performance problems with, but that is not correlated with this message ... I get this same message for my own pod usage on sandbox-nasa, but my pod works fine

I will update the onecloud lab instructions page to reflect. 

Thanks so much for reporting the issue!
