### ISSUE TITLE
Screenshot 2.5 in Create Student Folder lab doesn't match what I see

### ISSUE THREAD

**Issue by burkeazbill** [CNA-Tech/PKS-Ninja#203]
LabGuide: https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/CreateStudentFolder-SF6361

Screenshot 2.5 shows the first dropdown as: "base fork: **CNA-Tech/Students**"
and the other as "head fork: **afewellvmware/Students**"

However, my screen does not show "head fork", instead it shows "base repository: **CNA-Tech/Students**"
and the other shows "head repository: **burkeazbill/Students**"
![image](https://user-images.githubusercontent.com/6843161/52313019-ef5b5580-297a-11e9-893a-c29b1980891a.png)

My concern here is "base fork" & "head fork" vs. "base repository" & "head repository"

Aside from the text in those boxes, everything else looks fine so I am going ahead with clicking the "Create pull request" button.

Is this simply a Github UI update since the original post, or did I mis-click somewhere? This can be confusing to people new to this process if the screens don't match - I would update myself and submit a pull request if I was certain it was simply a UI update.

**Comment by afewell** [comment]
Hey Bill sorry for my delayed response, and this is a case where multiple roads lead to roam depending on how you do it, but the way you see above works great, the one big improvement is making updates on a seperate update branch which I didnt have in the guide at first, but I just updated the create your student folder with newer best practices if you want to check it out. 

Thanks!
