### ISSUE TITLE
library/frontend scan does not show any vulnerabilities

### ISSUE THREAD

**Issue by sammcgeown** [CNA-Tech/PKS-Ninja#218]
Step 4 in https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/IntroToHarbor-IH7914

The vulnerability scan should produce some vulnerabilities (shown in the screenshot) but does not.

Harbor reports Clair DB is not ready:
![2019-02-06_15-53-52](https://user-images.githubusercontent.com/5090072/52354051-9dbcd480-2a27-11e9-87ac-deb3d999fc42.png)

**Comment by natereid72** [comment]
This is expected behavior. Clair scan won't detect until the vuln sig update completely downloads.

**Comment by sammcgeown** [comment]
How long is this expected to take to update - PKS deployed Harbor at least 2 hours ago? If I'm a student following the lab guide I'll need to know this. Currently I can't proceed with the guide.

**Comment by natereid72** [comment]
Did you complete step 1.9 in https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/HarborTileInstall-HI3943

**Comment by sammcgeown** [comment]
No - the deployment was done using the Harbor Pipeline Install guide (https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/HarborPipelineInstal-IN4968). I'm currently running a PKS update with that configuration to see if it resolves it. Maybe the pipeline will need a tweak?

**Comment by natereid72** [comment]
yep, most likely. you can close this issue and open a new one that describes that out of sync issue. Long-term would be to update pipeline to set that value. meantime, you could implement a change to the lab guide for pks pipeline that instructs to make that change after install. As long as you uncheck pks on the apply changes, the harbor tile doesn't take long to update.

**Comment by sammcgeown** [comment]
Closed with PR #220
