### ISSUE TITLE
Lab 5 - cli-vm no uaac

### ISSUE THREAD

**Issue by natereid72** [CNA-Tech/PKS-Ninja#23]
UAAC does not exist on cli-vm. Was able to complete uaac tasks from opsman shell. Need to add uaac to cli-vm in template or change directions in lab guide.

**Comment by ragsgit** [comment]
While I tried UAAC commands from OpsMan VM, in my case, the UAAC user pksadmin already existed.

**Comment by sudhakarau1** [comment]
I installed uaac into the cli-vm using:
 apt-get update
 apt-get install ruby ruby-all-dev
 gem install cf-uaac

and the pksadmin user did not already exist for me

**Comment by afewell** [comment]
I could see reasons for doing it both ways, but I do think we should have instructions use UAAC for now at least until we get clear roadmaps and processes in place for template updates it is easier, and while it may be nice to show that UAAC is a common component on a jumpbox, I think its also nice to show users they can use it via bosh. I would be interested in hearing more opinions on this, we need to setup some structure around community feature request voting and what not, in the meantime though I think the most practical plan is to update the doc to ensure users use bosh, and we can hear any comments and feedback about which method should persist whenever we get formal planning organized for the next template update. Sound good?

**Comment by natereid72** [comment]
working on this correction today

**Comment by natereid72** [comment]
This issue has been resolved. Changed the directions to use opsman for uaac, changed uaac user create to pks-admin because the pks pipeline creates pksadmin user, and changed continuation of planesotter to bonus labs guide where it is fixed for our lab environment.
