### ISSUE TITLE
All v11 vAPPs are waiting on disks

### ISSUE THREAD

**Issue by polluxnl** [CNA-Tech/PKS-Ninja#235]
All vAPPs that are version 11 are stuck on waiting on disks in the vcore1-nl01 sanbox tenant.

**Comment by khbrady** [comment]
It appears to be a resource allocation issue, I get the following error just before my PKS build fails: The following vApps have resource allocations in excess of the thresholds configured by your OneCloud tenant administrator.

**Comment by afewellvmware** [comment]
Hi Polluxnl, 

It looks like some onecloud orgs dont support this template as well as others, I recommend requesting access to sandbox-nasa or emea or apac depending on your region (nasa is north/south america), you can open a ticket here to get access https://servicedesk.eng.vmware.com/servicedesk/customer/portal/7/create/259

I am also adding this to quick demo, and working to expand the v11 template to home and dedicated lab environments as onecloud is a best-effort resource. 

I am going to close this now as we know there are some onecloud partitions that do not work as well, right now vcore1 seems to be an issue but that isnt something we can get the onecloud team to change, but between sandbox-nasa/emea/apac and quick demo, one of those should work fine for you and if you have any ongoing issues with those let me know. Thanks!
