### ISSUE TITLE
Update vApp with NSX-T 2.3.0.2 OVAs

### ISSUE THREAD

**Issue by KeithRichardLee** [CNA-Tech/PKS-Ninja#24]
v10 vApp currently have NSX-T 2.3.0.0 OVA in E:\Downloads. Opening this issue so that NSX-T 2.3.0.2 OVA(s) are added

**Comment by afewellvmware** [comment]
we did not get to this so closing as out of date, however new strategy will be to have students downloading using their own provided licensing/access, first to simplify template maintenance, second to avoid complexities related to shipping bits and licensing access.
