### ISSUE TITLE
PKS the Hard Way: Step 11: Create NSX API Access Certificate

### ISSUE THREAD

**Issue by Mybarry** [CNA-Tech/PKS-Ninja#261]
The final step, eleven, in the NSX-T  2.3 Installation has an error in the command listed in:
 Execute the following command to register the certifcate for API access
It reads:
curl --insecure -u admin:'VMware1!' \
 -X POST \
 "https://$NSX_MANAGER_IP_ADDRESS/api/v1/node/services/http?action=apply_certificate&certificate_id=$CERTIFICATE_ID"
It should read:
curl --insecure -u admin:'VMware1!' \
 -X POST \
 "https://$NSX_MANAGER_IP_ADDRESS/api/v1/node/services/http?action=apply_certificate&certificate_id=$**certificate_id**"

**Comment by natereid72** [comment]
Why do you think the way it is, is an error? You're changing case of the reference to the bash env variable that is set earlier in the guide via 'export CERTIFICATE_ID=<Your Certificate ID>'

**Comment by natereid72-vmware** [comment]
It appears as though you received the same resolution on slack. Closing this issue.

**Comment by Mybarry** [comment]
Nate,
I only know as written it does not work for me. I had to change the case in the last command to have it work.

**Comment by natereid72** [comment]
Ok, I closed the issue. My guess is that you created the bash env variable with lower case instead of all caps as in the guide. nix env variables are case sensitive. Common practice is to use all caps with underscores to separate words when needed.

**Comment by Mybarry** [comment]
Nate,
Yes!  LOL. Never mind Im an idiot.  Doh!

Cheers,
Mich
