### ISSUE TITLE
Lab 9 and 10 have incorrect Concourse credentials

### ISSUE THREAD

**Issue by KeithRichardLee** [CNA-Tech/PKS-Ninja#30]
Lab 9 and 10 have incorrect Concourse credentials of nsx / vmware. Correct credentials are admin / VMware1!

**Comment by natereid72** [comment]
nsx/vmware works for me. admin/VMware1! does not. I think the current is correct.

**Comment by natereid72** [comment]
Yep, that's the difference. I don't think I've rebuilt with the v10 yet. I'll do that. Thanks for the heads up.

**Comment by natereid72** [comment]
Should be corrected with next PR merge

**Comment by natereid72** [comment]
resolved - can close
