### ISSUE TITLE
How can I view k8s dashboard? 

### ISSUE THREAD

**Issue by muercy** [CNA-Tech/PKS-Ninja#342]
Hi , How can I view k8s dashboard? 
And how can I get the username and password of the k8s masters and nodes? I want to login master with ssh.
when I push images from harbor, there is an error like this:  Failed to pull image "harbor.corp.local/library/app-server:v1": rpc error: code = Unknown desc = Error response from daemon: Get https://harbor.corp.local/v2/: x509: certificate signed by unknown authority.
Thanks a lot!

**Comment by afewell** [comment]
Hi @muercy the simplest way to get the dashboard is to use kubectl proxy, you can see exact steps on how to do it in step 2.2.11 of the [troubleshooting guide](https://github.com/CNA-Tech/PKS-Ninja/blob/a06eb6caa76eef8a2ce238e34dd8bc2c48cbc1af/LabGuides/PksTroubleshooting-PT8251/readme.md) 

To push or pull from harbor, you will need to make sure the docker engine you are using has the harbor certificate installed, if you are using cli-vm you need to manually install the certificate on cli-vm as detailed in the [Enable Harbor Client Secure Connections](https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/HarborCertExternal-HC7212) lab guide, and if you would like to deploy from harbor to a k8s cluster, you will need to make sure the bosh trusted cert feature is enabled, which you do in opsman in the bosh tile under security, there is a checkbox to include the opsman certificate in deployments, which will ensure harbor is signed with the opsman cert and that the k8s nodes are also configured with the opsman certificate whenever pks deploys a k8s node. After you enable this feature, you will need to apply changes in opsman and wait for a redeploy ~40 minutes. 

Thanks!
