### ISSUE TITLE
Order of Getting started

### ISSUE THREAD

**Issue by sudhakarau1** [CNA-Tech/PKS-Ninja#45]
Step 2.2.3 of https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/CreateStudentFolder-SF6361 seems to require that step 7 in https://github.com/CNA-Tech/PKS-Ninja/tree/master/Courses/GettingStarted-GS3861 need to come before Step 4?

**Comment by ragsgit** [comment]
Student folder step is only needed if you want to edit and contribute.  Pick one of the courses and follow the steps there.

**Comment by afewell** [comment]
I updated the instructions to reflect that the creating your student folder lab guide can be done from any computer with github, and noted that if the participant would like to complete from the lab environment I provided pointer to Getting access to lab environment course guide. 

Thanks!
