### ISSUE TITLE
PKS Pipeline Workaround

### ISSUE THREAD

**Issue by fitz0017** [CNA-Tech/PKS-Ninja#49]
Replacing the below files into the template v10 with the ones I've attached here should allow the pks ci pipeline to work using Nathan's commenting out the syslog method.  Had to attach as .txt files, just need to chop that off.

[install-pks-pipeline.yml.txt](https://github.com/CNA-Tech/PKS-Ninja/files/2677780/install-pks-pipeline.yml.txt)
[task.sh.txt](https://github.com/CNA-Tech/PKS-Ninja/files/2677783/task.sh.txt)
[task.yml.txt](https://github.com/CNA-Tech/PKS-Ninja/files/2677786/task.yml.txt)
[config-pks-1.1.sh.txt](https://github.com/CNA-Tech/PKS-Ninja/files/2677790/config-pks-1.1.sh.txt)

        nsx-t-ci-pipeline/tasks/config-pks/task.yml
      
        nsx-t-ci-pipeline/tasks/config-pks/task.sh
      
        nsx-t-ci-pipeline/tasks/config-pks/config-pks-1-1.sh

        nsx-t-ci-pipeline/pipelines/install-pks-pipeline.yml

**Comment by ragsgit** [comment]
I suppose we have to WinSCP these files from the ControlCenter Desktop to the CLI-VM? Is that correct or there is some other way?

**Comment by afewell** [comment]
That is a good point rag, one thing you could do is add these files to a personal github repo and then clone them down from the lab environment, but we should also centralize that method for updates like this. I need to setup a different repo in any case to host the infrastructure code and any other lab topology definition documents as we need to version control the standard lab topologies as well, and it would be good to have a spot there or somewhere where we can host assets until the template is available. That being said, I have already been able to use tango to deploy blueprints to onecloud and I am working to making that capable of configuring and deploying the lab to an arbitrary vcenter endpoint. Once I get all that in place we can move towards a ci/cd model for lab templates

**Comment by natereid72** [comment]
No idea why this isn't working for me. You guys have got this to work? I have a script file that makes all of the changes exactly as the attached files, and it still fails. 
![image](https://user-images.githubusercontent.com/45366367/50369771-ac7b2500-0568-11e9-8929-3d99fdc122af.png)

**Comment by natereid72** [comment]
What worked for me was to restrict the install releases to opsman 2.3.0 and pks 1.2.0. I kept the comments on all of the syslog lines, so not sure how much are needed or not. I was able to find a script to expose tile properties that should lead to resolving the differences between 2.3 om and 2.3.+ om that causes the issue. For now, I have a script that sets the pipeline files to work for the pks pipeline install. I'll post it on the slack channel.

**Comment by natereid72** [comment]
For those not on the slack channel:

Stop-gap to resolve cli-vm DNS resolution and Concourse pipeline PKS install.

You can run this script after deploying your v10 lab template, to fix the DNS client issue and the PKS pipeline issue.

1. From cli-vm, git clone https://github.com/natereid72/PKS-Ninja-Lab-Patch.git
2. As per the readme, execute the shell script (Execute source cc-p1.sh at the command line on cli-vm)
3. then follow lab guides as normal
No need to copy or edit files this way. Just run the script and v10 will work per the guides.

**Comment by afewellvmware** [comment]
All related guides have been updated with instructions to use Nate's patch on new template load, closing
