### ISSUE TITLE
Multiple v12 templates have internet access problems

### ISSUE THREAD

**Issue by afewellvmware** [CNA-Tech/PKS-Ninja#507]
It appears the vPodrouter in the attached templates is implementing URL filtering and blocking http/s access to most public sites. 

[Workaround available here](https://confluence.eng.vmware.com/display/CNA/Multiple+v12+templates+have+internet+access+problems) 
[Video Walkthrough of the Issue Resolution Here](https://youtu.be/RrNuBXbXuzo)

The resolution above is on a VMware internal server as it contains details we did not want to post publicly. If you are outside of VMware and need to resolve this issue, please reach out to the #PksNinjaLabs channel on the VMware Code slack domain or open an issue ticket so we can work with you directly to provide a resolution, updated templates that already have this patch in place should be available within a few days.

**Comment by afewellvmware** [comment]
https://github.com/CNA-Tech/PKS-Ninja-vApp-Templates/tree/master/v12/Milestones/6425/Patches/507

**Comment by afewell** [comment]
While the patch will be integrated into the next release, there is a simple workaround for this issue that you can apply to the existing v12 templates directly from the control center in your running vApp. 

Huge thanks to @ChrisJLittle for providing the workaround below!

```text
ssh to vpodrouter as root (W@tch3r!) - vpodrouter is simply named "router" in the lab dns so ssh to root@router
root@vPodRouter-HOL:~# mv /root/iptablescfg.sh /root/iptablescfg.sh.orig
root@vPodRouter-HOL:~# mv /root/getrules.sh /root/getrules.sh.orig
root@vPodRouter-HOL:~# mv /etc/init.d/holuser /home/holuser/
root@vPodRouter-HOL:~# passwd root (set to VMware1!)
root@vPodRouter-HOL:~# reboot
```
