### ISSUE TITLE
Build Tracker for v12-Baseline-0.6

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#508]
Issue to track & document the build process for v12-Baseline-0.6

**Comment by afewellvmware** [comment]
Completed documenting & applying all patches for Baseline-0.6, initiate template shutdown

**Comment by afewellvmware** [comment]
Completed shutdown & saved to wdc-vcd01-cnabu-t org in the PKS-Base-vPod catalog. Spawned new template "CNABU-PKS-Ninja-v12-Baseline-0.6-test1" to validate. Validation still needs to be completed.

**Comment by afewellvmware** [comment]
Found that the CPU allocation needs further tuning per issue #503. Adjusting CPU allocation now, and will initiate validation shortly

**Comment by afewellvmware** [comment]
Updated Patch #503 with correct allocations, applied corrected allocations to Baseline-0.6, and saved updated template also as Baseline-0.6, initiating validation

**Comment by afewellvmware** [comment]
Completed local validation, finalizing build @ initiating transfer, track via transfer ticket #514
