### ISSUE TITLE
multiple v12 templates need their labstartup script timer extended

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#519]
Due to oversubscription and variable performance on different onecloud orgs, we are seeing increased frequency of the labstartup script timers failing and placing a failed status watermark on the desktop. In many of these cases after waiting longer for the template to finish booting, it works fine, but still displays a failed watermark. 

Accordingly, we should extend the duration of the timeout value for the labstartup script and advise people to wait up to an hour for the template to complete booting.

**Comment by afewellvmware** [comment]
Patch Ready: https://github.com/CNA-Tech/PKS-Ninja-vApp-Templates/tree/master/v12/Milestones/6425/Patches/519
