### ISSUE TITLE
transfer template "CNABU-PKS-Ninja-v12-NsxtReady-0.4" for FEL/VLP/QD Access

### ISSUE THREAD

**Issue by afewellvmware** [CNA-Tech/PKS-Ninja#521]
Opened ticket INTSD-13689 to initiate transfer. 

Ticket status here: https://servicedesk.eng.vmware.com/servicedesk/customer/portal/7/INTSD-13689

**Comment by pks-ninja-labs-owners** [comment]
Still no results from help desk, their ticket reported it as completed though there is no evidence it was ever completed, still not available. Added another request for escalation to cosd and initiated manual transfer as an attempt to reconcile since help desk requests are ineffective.
