### ISSUE TITLE
Transfer Template CNABU-PKS-Ninja-v12-ClusterReady-0.5 to vcore3-us01 for sandbox-eval

### ISSUE THREAD

**Issue by afewellvmware** [CNA-Tech/PKS-Ninja#536]
Initiating manual transfer per attached screenshot 
![image](https://user-images.githubusercontent.com/34895636/64278672-28a07780-cf02-11e9-8db4-b3a045515930.png)

**Comment by pks-ninja-labs-rw** [comment]
Confirmed template is available on destination org
