### ISSUE TITLE
Login to vcenter webclient gives invalid credentials error

### ISSUE THREAD

**Issue by rkamalon** [CNA-Tech/PKS-Ninja#541]
I am facing issue logging into the vCenter server(vcsa-01a.corp.local) with ac administrator@vsphere.local and Password as VMware1!, as mentioned in the README.txt file. 

The template I am using is CNABU-PKS-Ninja-v12-ClusterReady-0.4

Best regards,
Roshan Kamalon
![vc-login-issue](https://user-images.githubusercontent.com/50742379/62917631-a0bfc580-bdba-11e9-9683-a1f891294ff4.PNG)

**Comment by afewellvmware** [comment]
Hi @rkamalon sorry for the inconvenience, we did not update the readme file on the desktop, some updated templates will be coming out shortly, but in the meantime you can view the correct details here: https://github.com/CNA-Tech/PKS-Ninja-vApp-Templates/blob/master/v12/Milestones/6425/Patches/490/Assets/README.txt


There are some other known issues with that template version in case you run into any other issues, you can see the known issues at the following link, an updated template (ClusterReady-0.5) is done and in the process of transferring to the catalog now, but in the meantime if you run into issues you can see the workarounds here: https://github.com/CNA-Tech/PKS-Ninja/issues?utf8=%E2%9C%93&q=label%3AAppliesTo%2FvAppTemplate%2Fv12-ClusterReady-0.4++milestone%3AMilestone6425+

Thanks!
