### ISSUE TITLE
Do not place your t1-pks-mgt on the Edge Cluster

### ISSUE THREAD

**Issue by Mybarry** [CNA-Tech/PKS-Ninja#573]
This is for the PKS The HardWay Lab Guide for PKS 1.4.  In the lab it shouldn't matter, but we should call out you do not want to do this in Production, etc. If you put the T1 on the Edge Cluster you get a T1-SR and your E/W routing will no longer be distributed but will be hair pinned  through the T1-SR.  Also you need to be very careful about having the T0- SR and the T1-SR end up on the SAME Edge Node. Placement is crucial. This would be more deep dive stuff but maybe just add a caveat that this is a LAB and not Prod design.

**Comment by afewellvmware** [comment]
Thanks for bringing this issue to light @Mybarry !!
This is a new issue so you can register the points for the "#2 Report an Issue" in the competition!
If you would like to add an update to the lab guide with some notes to resolve this, please do so and when you submit the update PR, please include the line "Fixes #573" in the comment and you will can get points for "#4 Resolve an Issue", and get points for "#3 Commit an update/improvement" and your lines committed will also count toward "#7 Git Like a Borg Points Competition"! In the competition a single commit can qualify for multiple awards, but you will have to create a separate points registration entry for each category your update qualifies you for. 

I will leave this issue open until someone updates the lab guide per your recommendation

Thank you!
