### ISSUE TITLE
Screenshot is missing for NSX-T configuration manual

### ISSUE THREAD

**Issue by batchamalick** [CNA-Tech/PKS-Ninja#580]
The screen shot for the manual installation is missing screenshot 1.6
https://github.com/CNA-Tech/PKS-Ninja/tree/Pks1.4/LabGuides/NsxtManualInstall-IN1497

**Comment by batchamalick** [comment]
image for Screenshot 1.11 missing as well

**Comment by p-alexisv** [comment]
PR #652 submitted for this.

**Comment by p-alexisv** [comment]
PR has been approved.  The screenshots are there now.  I think we can close this.  cc @afewell @riazvm

**Comment by p-alexisv** [comment]
Fixed by PR #652
