### ISSUE TITLE
Accessing First PKS Cluster Lag Guide throwing error

### ISSUE THREAD

**Issue by Mybarry** [CNA-Tech/PKS-Ninja#635]
I can successfully perfrom step 1 and pull down the credetials to the cli-vm  using pks cli. But Step 2 is failing with the following error:
ubuntu@cli-vm:~/.kube$ kubectl get nodes
Unable to connect to the server: x509: certificate is valid for localhost, not my-cluster.corp.local

Is there a solution to this problem?

**Comment by Mybarry** [comment]
So my-cluster.corp.local is hard coded in the DNS forward zone. when you deploy my-cluster.corp.local via the cli it might get a different IP. To resolve this you need to edit the DNS entry for my-cluster to match the IP address it actually get from the LB-VIP Pool. Then you need to clear the local DNS cach on the cli-vm: sudo systemd-resolve --flush-cache. Then validate the IPs match by running dig my-cluster.corp.local and compare it to the outpout of pks cluster my-cluster and make sure it matches the K8s Master IP..

**Comment by afewellvmware** [comment]
Awesome @Mybarry I was thinking it may be DNS glad you figured it out. You learned something valuable here and shared the resolution with the community, so for the competition please give yourself credit for opening and resolving an issue. 

Thanks!
