### ISSUE TITLE
Ops Manager Authorization Request Error following PKS install via EPMC

### ISSUE THREAD

**Issue by p-alexisv** [CNA-Tech/PKS-Ninja#660]
Following installation of PKSv1.5 via Enterprise PKS Management Console (EPMC), trying to log on to Ops Manager UI using `https://opsman.corp.local` URL would result in an Authorization Request Error with the following message:

```
Invalid redirect 
https://opsman.corp.local/auth/cloudfoundry/callback 
did not match one of the 
registered values

Authorization Request Error
There was an error. The request for authorization was invalid.
```

This is very likely because EPMC appears to configure Ops Manager authentication using the IP address in the URL.  This is evidenced by the fact that it is not required by EPMC to set up Ops Manager FQDN in DNS before completing the configuration.  When Ops Manager authentication is configured using IP address (not FQDN) in the URL, that URL is persists in Ops Manager setting for auth.

As a workaround, the URL with the Ops Manager IP address should be used.  E.g., `https://10.40.14.xx` instead of `https://opsman.corp.local`

**Comment by afewellvmware** [comment]
Closing as overlapping with #661
