### ISSUE TITLE
when issuing kubectl command, i get connection refused

### ISSUE THREAD

**Issue by leoncozzi** [CNA-Tech/PKS-Ninja#664]
ubuntu@cli-vm:~/.kube$ kubectl get nodes
The connection to the server my-cluster.corp.local:8443 was refused - did you specify the right host or port?
ubuntu@cli-vm:~/.kube$

**Comment by p-alexisv** [comment]
I would run the following steps to troubleshoot.  I'm not sure if you know/not know bosh so I'm just gonna provide some details here.

1) In the cli-vm, run `pks cluster my-cluster` and see what is the Kubernetes Master IP.  That IP address would be the Load Balancer IP address of the k8s cluster.  Just also make sure that this IP address matches the output of `nslookup my-cluster`.

2) In the NSX Manager, search the above LB IP address. In the search results, click the item that is a virtual server.  Then, find the IP address of the pool member of this virtual server.  This IP would be the address of the master VM.

3) In the Control-center Chrome browser, get the bosh command line credentials via https://opsman.corp.local/api/v0/deployed/director/credentials/bosh_commandline_credentials.  Copy the value of the `credentials` key.

4) SSH to the Ops Manager VM.  Run `export <value>`.  Then, run `bosh vms` and then find the status of the VM's of the cluster (identified by deployment name having `service-instance_*`.  Find the IP address of the pool member (from step #2) in this output.  It should be the master VM. Note what is the value of the `Process state`.  I presume it is not `running` in your case, and if so, run `bosh instances -p` to know which process is failing.

I guess the next actions depend on the output of the above.

Hope this helps.

**Comment by leoncozzi** [comment]
Thank you.

yep, thats the issue.

ubuntu@cli-vm:/etc$ nslookup my-cluster
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   my-cluster.corp.local
Address: 10.40.14.34

ubuntu@cli-vm:/etc$ pks cluster my-cluster

Name:                     my-cluster
Plan Name:                small
UUID:                     13255aa0-09a8-4eb8-b1d7-6a8872aa7429
Last Action:              CREATE
Last Action State:        succeeded
Last Action Description:  Instance provisioning completed
Kubernetes Master Host:   my-cluster.corp.local
Kubernetes Master Port:   8443
Worker Nodes:             2
Kubernetes Master IP(s):  10.40.14.36
Network Profile Name:

ubuntu@cli-vm:/etc$

I assume i just update the DNS server?

**Comment by p-alexisv** [comment]
Yes, I would update the DNS server to match.
