### ISSUE TITLE
Transfer template "HOL-2031-v0.11" from HOL-DEV to cnabu-t org

### ISSUE THREAD

**Issue by pks-ninja-labs-owners** [CNA-Tech/PKS-Ninja#675]
Initiated transfer manually via cms tool 10/1 @ 1:00PM PST

![image](https://user-images.githubusercontent.com/55507284/65997825-f88bbc00-e44e-11e9-8213-d21e484cdfac.png)

**Comment by pks-ninja-labs-rw** [comment]
decided not to maintain seperate version of hol template, preferred usage is via HOL, if needed in onecloud users should be able to access from HOL global catalogs
