### ISSUE TITLE
DNS Wrong, how can i update it.

### ISSUE THREAD

**Issue by leoncozzi** [CNA-Tech/PKS-Ninja#680]
The DNS server has the wrong entry. I have not been able to find the DNS server details. On the Ubuntu VM there is no Bind details. Can someone confirm how i change this DNS entry?
pks cluster my-cluster shows   10.40.14.36
whilst
nslookup my-cluster shows  10.40.14.34
ubuntu@cli-vm:/etc$ pks cluster my-cluster

Name:                     my-cluster
Plan Name:                small
UUID:                     13255aa0-09a8-4eb8-b1d7-6a8872aa7429
Last Action:              CREATE
Last Action State:        succeeded
Last Action Description:  Instance provisioning completed
Kubernetes Master Host:   my-cluster.corp.local
Kubernetes Master Port:   8443
Worker Nodes:             2
Kubernetes Master IP(s):  10.40.14.36
Network Profile Name:

ubuntu@cli-vm:/etc$ nslookup my-cluster
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   my-cluster.corp.local
Address: 10.40.14.34

**Comment by p-alexisv** [comment]
You should be able to change the IP address in the DNS server in the ControlCenter desktop (Windows machine).  Go to Control Panel->Admin Tools->DNS->ControlCenter->Forward Lookup Zones->my-cluster and then modify the IP address.

After you make that change, you may want to restart systemd-resolved in the cli-vm to pick up the changes right away.

**Comment by leoncozzi** [comment]
thankyou!
