### ISSUE TITLE
decryption password of VMware1! does work on opsman on PKS-Ninja-v12-Pks1.5Installed-epmc-0.1

### ISSUE THREAD

**Issue by leoncozzi** [CNA-Tech/PKS-Ninja#688]
I have loaded PKS-Ninja-v12-Pks1.5Installed-epmc-0.1 multiple times on different Onecloud environments. The decryption password of VMware1! does work on opsman on PKS-Ninja-v12-Pks1.5Installed-epmc-0.1

**Comment by afewellvmware** [comment]
@leoncozzi yes sorry some things are a little different with epmc, it generates unique passwords for each component it installs, so you need to open a browser tab to epmc and look at the deployment metadata to find passwords and also IP addresses of epmc installed components, the IP addresses also will not be exactly the same as other labs where manual installation was used, but pretty easy to find the info in the epmc web console

**Comment by leoncozzi** [comment]
When i log into the EPMC as part of this lab, it does not show any installed components. It only offers a link to install PKS.

**Comment by leoncozzi** [comment]
Thank you. Found it!
