### ISSUE TITLE
EPMC 1.6 Automated NAT Deployment guide 

### ISSUE THREAD

**Issue by sudhakarau1** [CNA-Tech/PKS-Ninja#703]
Not sure if someone already created a guide for https://docs.pivotal.io/pks/1-6/console/prereqs-nsxt-automatednat.html? I created one here https://github.com/sudhakarau1/PKS-Ninja/blob/Pks1.6/LabGuides/PksInstallEpmc-PI9606/readme-autonat.md.

**Comment by afewellvmware** [comment]
Hey Freddy I think we discussed this one so I am going to close it out. I would love to go through this one if I get a chance or do a diff between this and the other guide I made, I am not partial to anything in particular except I used specific IP pool ranges in the ClusterReady template so want to make sure its aligned. I am going to close this for now, thanks again!
