### ISSUE TITLE
NSX-T Manual Install Steps

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#8]
If anyone wants to do it, would like to add manual installation lab for NSX-T. This would be intended to go along with lab 2, but would ideally be a second lab. If anyone wants to document, please use a similar style to Lab2, and please add it to the PKS-Ninja/LabGuides/Bonuslabs directory. 

Instructions:
Fork the PKS-Ninja repo and clone your fork to your local machine, navigate to the bonuslabs directory and mkdir NsxtManualInstall and then put your documentation in a readme.md file in that directory. 

then git add . && git commit -m "Added NSXT Manual Install guide to bonus labs" && git push

Then after you push check your fork of the repo on github to make sure you see the update in your bonuslabs directory, then go to the PKS-Ninja github page and open a pull request with your changes. 

Thank you!

**Comment by afewellvmware** [comment]
Nate Reid finished this, closing
