### ISSUE TITLE
add guidance to lab 2 for required NSXT install

### ISSUE THREAD

**Issue by afewell** [CNA-Tech/PKS-Ninja#9]
In updated onecloud template, NSX-T needs to be installed before lab 2 is attempted, this can be done by skipping ahead to lab 9 and doing an automated NSX-T install then when complete proceeding with lab 2. 

Text needs to be updated in Lab 2 readme to explain this

Thanks!

**Comment by afewellvmware** [comment]
Nate Reid finished this, closing
