### ISSUE TITLE
link broken in  NSX-T Manual Installation

### ISSUE THREAD

**Issue by elnemesisdivina** [CNA-Tech/PKS-Ninja#99]
Yo fellows I trying to acces the link below and seems like it is broken 

https://github.com/CNA-Tech/PKS-Ninja/tree/master/Staging/LabGuides/NSX-Hard-Way

**Comment by natereid72** [comment]
That guide appears to be in the staging directory. https://github.com/CNA-Tech/PKS-Ninja/tree/master/Staging/LabGuides/NsxtManualInstall-IN1497

That's where it started at, so the link to it is probably not completed for final inclusion in promoted to guides yet.

**Comment by natereid72-vmware** [comment]
Fixed
